include:
  - project: "observability/shared/gitlab-jobs"
    file:
      - "oss-scan-template-v1.yml"

# verification job run upon GitLab PR
gitlab-pr-build:
  only:
    - branches
  variables:
    PR_BUILD: splunk-apm
    BRANCH: $CI_COMMIT_REF_NAME
  trigger:
    project: observability/gdi/lambda-layers
    strategy: depend
