#!/bin/bash

# no metrics
export OTEL_METRICS_EXPORTER=none
# OTLP traces exporter
export OTEL_TRACES_EXPORTER="${OTEL_TRACES_EXPORTER:-otlp}"
# tracecontext, baggage propagation
export OTEL_PROPAGATORS="${OTEL_PROPAGATORS:-tracecontext,baggage}"
# SA default endpoint - if using jaeger-thrift
export OTEL_EXPORTER_JAEGER_ENDPOINT="${OTEL_EXPORTER_JAEGER_ENDPOINT:-http://127.0.0.1:9080/v1/trace}"
export OTEL_TRACES_SAMPLER="${OTEL_TRACES_SAMPLER:-always_on}"

# disable non-lambda resource providers
export OTEL_JAVA_DISABLED_RESOURCE_PROVIDERS="${OTEL_JAVA_DISABLED_RESOURCE_PROVIDERS:-\
io.opentelemetry.sdk.extension.resources.OsResourceProvider,\
io.opentelemetry.sdk.extension.resources.ProcessResourceProvider,\
io.opentelemetry.sdk.extension.aws.resource.BeanstalkResourceProvider,\
io.opentelemetry.sdk.extension.aws.resource.Ec2ResourceProvider,\
io.opentelemetry.sdk.extension.aws.resource.EcsResourceProvider,\
io.opentelemetry.sdk.extension.aws.resource.EksResourceProvider}"

# splunk token header if OLTP
if [ -n "$SPLUNK_ACCESS_TOKEN" ] && [ "$OTEL_TRACES_EXPORTER" = "otlp" ]
then
    HEADER="X-SF-TOKEN=$SPLUNK_ACCESS_TOKEN,"
    export OTEL_EXPORTER_OTLP_HEADERS="$HEADER""${OTEL_EXPORTER_OTLP_HEADERS}"
fi