#!/bin/bash
set -e

# specifically unset splunk variables so language-level instrumentations won't talk
# directly to ingest (unless collector is disabled)
SLLCE="${SPLUNK_LAMBDA_LOCAL_COLLECTOR_ENABLED}"
# case conversion only in bash 4+... :-(
if [ "${SLLCE}" != "false" ] && [ "${SLLCE}" != "FALSE" ] && [ "${SLLCE}" != "0" ]
then
  unset SPLUNK_REALM
  unset SPLUNK_ACCESS_TOKEN
fi


# no otel metrics
export OTEL_METRICS_EXPORTER=none

# otlp traces exporter
export OTEL_TRACES_EXPORTER="${OTEL_TRACES_EXPORTER:-otlp}"
# http/protobuf protocol
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL="${OTEL_EXPORTER_OTLP_TRACES_PROTOCOL:-http/protobuf}"

# tracecontext, baggage propagation
export OTEL_PROPAGATORS="${OTEL_PROPAGATORS:-tracecontext,baggage}"

# no sampling
export OTEL_TRACES_SAMPLER="${OTEL_TRACES_SAMPLER:-always_on}"

# default flush timeout if not set
export OTEL_INSTRUMENTATION_AWS_LAMBDA_FLUSH_TIMEOUT="${OTEL_INSTRUMENTATION_AWS_LAMBDA_FLUSH_TIMEOUT:-30000}"
