#!/bin/bash

# no metrics
export OTEL_METRICS_EXPORTER=none

# otlp traces exporter
export OTEL_TRACES_EXPORTER="${OTEL_TRACES_EXPORTER:-otlp}"
# otlp-grpc protocol
export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL="${OTEL_EXPORTER_OTLP_TRACES_PROTOCOL:-grpc}"

# tracecontext, baggage propagation
export OTEL_PROPAGATORS="${OTEL_PROPAGATORS:-tracecontext,baggage}"

# no sampling
export OTEL_TRACES_SAMPLER="${OTEL_TRACES_SAMPLER:-always_on}"

# splunk token header if OLTP
if [ -n "$SPLUNK_ACCESS_TOKEN" ] && [ "$OTEL_TRACES_EXPORTER" = "otlp" ]
then
    HEADER="X-SF-TOKEN=$SPLUNK_ACCESS_TOKEN,"
    export OTEL_EXPORTER_OTLP_HEADERS="$HEADER""${OTEL_EXPORTER_OTLP_HEADERS}"
fi


# splunk REALM support
if [ -n "$SPLUNK_REALM" ]
then

    if [ -z "$SPLUNK_METRICS_ENDPOINT" ]
    then
        export SPLUNK_METRICS_ENDPOINT="https://ingest.${SPLUNK_REALM}.signalfx.com"
    fi

    if [ "$OTEL_TRACES_EXPORTER" = "otlp" ] && [ -z "$OTEL_EXPORTER_OTLP_ENDPOINT" ]
    then
        export OTEL_EXPORTER_OTLP_ENDPOINT="https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace/otlp"
    elif [ "$OTEL_TRACES_EXPORTER" = "jaeger" ] && [ -z "$OTEL_EXPORTER_JAEGER_ENDPOINT" ]
    then
        export OTEL_EXPORTER_JAEGER_ENDPOINT="https://ingest.${SPLUNK_REALM}.signalfx.com/v2/trace"
    fi
fi

# validation - realm must have token
if [ -n "$SPLUNK_REALM" ] && [ -z "$SPLUNK_ACCESS_TOKEN" ]
then
    echo "CONFIGURATION ERROR! SPLUNK_REALM is set but SPLUNK_ACCESS_TOKEN is not present. This may prevent data export to Splunk Observability Cloud."
fi

# validation - either realm or relevant exporter endpoint
if [[ -z "$SPLUNK_REALM" && ( "$OTEL_TRACES_EXPORTER" = "otlp" && -z "$OTEL_EXPORTER_OTLP_ENDPOINT" || "$OTEL_TRACES_EXPORTER" = "jaeger" && -z "$OTEL_EXPORTER_JAEGER_ENDPOINT" ) ]]
then
    echo "CONFIGURATION ERROR! Neither SPLUNK_REALM nor exporter endpoint defined. Traces will not be exported."
fi